name: trinity_wizards
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  flutter_bloc: ^8.1.3
  logger: ^1.3.0
  bloc: ^8.1.1
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  injectable: ^2.1.1
  get_it: ^7.6.0
  auto_route: 7.1.0
  flutter_screenutil: 5.0.0
  google_fonts: ^4.0.4
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  auto_route_generator: ^7.0.0
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/